# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wakame-adapters-tengine"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["axsh"]
  s.date = "2011-10-30"
  s.description = "wakame-adapters-tengine is ..."
  s.email = "axsh"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "lib/apis/ec2.rb",
    "lib/apis/wakame.rb",
    "lib/controllers/controller.rb",
    "tama.rb",
    "test/generic_test.rb",
    "test/real_test.rb",
    "test/test_files/describe_images.json",
    "test/test_files/describe_instances.json",
    "test/test_files/host_nodes.json",
    "test/test_files/run_instances.json",
    "test/test_files/terminate_instances.json"
  ]
  s.homepage = "https://github.com/axsh-dev/wakame-adapters-tengine"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "wakame-adapters-tengine is ..."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<right_aws>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<right_aws>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<right_aws>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

